### ISSUE TITLE
Thomas Frommann (BMW) in town Feb 10th - meet with him! (he prefers ONE point of contact)

### ISSUE THREAD

**Issue by JBB** [cs210/AXLES#1]
Hi gang,
As you saw, Thomas from BMW and Alan from Google have engaged, so you are in great shape with industry connections.  Thomas mentioned to me he will be in town and available to meet with you in person February 10th.  Definitely recommend making a meeting happen with as many of your team members present as possible.

Two other notes:
1. Thomas prefers to have ONE point of contact to communicate with on the team
2. Thomas (and BMW) prefer to communicate using Microsoft Teams.
2a. We have ordered a Surface Hub2s for the Loft which you can use for working sessions/calls with BMW folks like Thomas if you like

**Comment by akhand42** [comment]
This is incredible news! We have a virtual call set up with both Alan and Thomas on the morning of February 6th. Connecting with Thomas in person later would be great too!
1.  @emmaald will be the point of contact person on the team.
2. We have set up a Microsoft Teams to communicate with Thomas (and BMW). Linking it [here (cs210axles.teams.com)](https://teams.microsoft.com/l/team/19%3a647fbdfa6abe4bf0a0105de8e5c9abf8%40thread.skype/conversations?groupId=70320031-f1e5-44f9-ae00-d1865b6db172&tenantId=bcda95a1-ff36-43de-8f86-81e7a605493a) in case someone on the teaching team would like to join in order to keep track of our communications with BMW.
2a. A Microsoft Hub 2 would definitely be a positive change to our lives because none of us are very familiar with Microsoft Teams at the moment.
3. I have added @swathiiyer2 to our Notion workspace which is where we are going to be documenting our meetings, thoughts, benchmarking, brainstorming, ideas, etc.

**Comment by JBB** [comment]
Also for future interactions with Thomas, if your team tends to stay up to midnight consider having calls with him then which is 9am in Germany. Or not - just something to consider

**Comment by JBB** [comment]
Folks, we now have a [Surface Hub2](https://www.microsoft.com/en-us/surface/business/surface-hub-2) in the Loft.  It needs to be set up, but this should unlock more collaborative forms of communicating with Thomas and his team.  Feel free to come by and play with it (Jaewoo is planning to start setting it up around 5pm today)
